# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            JDC
tagline:          "Junior Defender Camp 2017"
description:      "Junior Defender Camp 2017"
url:              https://github.com/ntu-offsec
baseurl:          /jdc/

author:
  name:           'NTU OFFSEC'
  url:            httpw://www.facebook.com/ntu.offsec

paginate:         1

# Custom vars
version:          1.0.0
